use_frameworks!

platform :ios, '8.0'

target 'HHTableListViewController_Example' do
  pod 'HHTableListViewController', :path => '../'

  target 'HHTableListViewController_Tests' do
    inherit! :search_paths

    
  end
end
